posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
  path('',views.posts_list,name="list"),
  path('<slug:slug>',views.post_page,name="page")
]

zenithGoals/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls'))
]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model) :
  title = models.CharField(max_length=255)
  description = models.TextField()
  slug = models.SlugField()
  date = models.DateField(auto_now=True)

posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse;

# Create your views here.

def posts_list(request):
  # this way we can do fetching data in django orm
  posts = Post.objects.all().order_by('-date')
  return render(request,'posts/posts_list.html',{'posts':posts})


def post_page(request,slug):
  post = Post.objects.get(slug=slug)
  return render(request,'posts/post_page.html',{'post':post})

zenithGoals/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
  # return HttpResponse('Hello World ! Im home .')
  return render(request,'home.html')


def about(request):
  # return HttpResponse('this is our about page. ')
  return render(request,'about.html')

posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
{{post.title}}
{% endblock title %}


{% block content %}

<section>
   <h3> {{post.slug}}</h3>
   <p>{{post.description}}</p>
   <p>{{post.date}}</p>
</section>


{% endblock  %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %} 
{% block title %} posts {% endblock %} {% comment %}
content here {% endcomment %} {% block content %}

<section>
  {% for post in posts %}
  <article>
    <h2>Title : <a href="{% url 'posts:page' slug=post.slug %}">{{post.title}} </a></h2>
    <small> {{post.date}}</small>
    <p>Description : {{post.description}}</p>
    <p>{{post.slug}}</p>
  </article>

  {% endfor %}
</section>

{% endblock %}

templates/about.html
{% extends "./layout.html" %}

{% comment %} title  {% endcomment %}

{% block title %}
about
{% endblock %}


{% comment %} content here   {% endcomment %}

{% block content %}
  <h1>About</h1>
  <p> check our <a href="/">home</a> page </p>
{% endblock %}

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home </title>
</head>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<body>
  <h1>Home</h1>

  <p> check our <a href="/about">about</a> page </p>
</body>
</html>

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} zenithGoals {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">Home</a>
      <a href="/about">about</a>
      <a href="{% url 'posts:list' %}">posts</a>
    </nav>

    <main>{% block content%} {% endblock %}</main>
  </body>
</html>